export const TEAM_REQUIRED_DUMMY: Record<string, { skill_id: number; target_level: number; is_core: boolean }[]> = {
  "소재개발팀": [
    { skill_id: 1, target_level: 3, is_core: true },
    { skill_id: 34, target_level: 3, is_core: true },
    { skill_id: 35, target_level: 3, is_core: true },
    { skill_id: 36, target_level: 3, is_core: true },
    { skill_id: 120, target_level: 2, is_core: true },
    { skill_id: 22, target_level: 2, is_core: false },
    { skill_id: 24, target_level: 2, is_core: false },
    { skill_id: 33, target_level: 2, is_core: false },
  ],
  "소재개발팀2": [
    { skill_id: 5, target_level: 3, is_core: true },
    { skill_id: 28, target_level: 3, is_core: true },
    { skill_id: 29, target_level: 3, is_core: true },
    { skill_id: 30, target_level: 3, is_core: true },
    { skill_id: 61, target_level: 2, is_core: true },
    { skill_id: 31, target_level: 2, is_core: false },
    { skill_id: 32, target_level: 2, is_core: false },
    { skill_id: 63, target_level: 2, is_core: false },
  ],
  "제조기술팀": [
    { skill_id: 14, target_level: 3, is_core: true },
    { skill_id: 26, target_level: 3, is_core: true },
    { skill_id: 66, target_level: 3, is_core: true },
    { skill_id: 68, target_level: 3, is_core: true },
    { skill_id: 83, target_level: 2, is_core: true },
    { skill_id: 69, target_level: 2, is_core: false },
    { skill_id: 70, target_level: 2, is_core: false },
    { skill_id: 89, target_level: 2, is_core: false },
  ],
  "설비기술팀": [
    { skill_id: 16, target_level: 3, is_core: true },
    { skill_id: 39, target_level: 3, is_core: true },
    { skill_id: 47, target_level: 3, is_core: true },
    { skill_id: 79, target_level: 3, is_core: true },
    { skill_id: 86, target_level: 2, is_core: true },
    { skill_id: 71, target_level: 2, is_core: false },
    { skill_id: 97, target_level: 2, is_core: false },
    { skill_id: 103, target_level: 2, is_core: false },
  ],
  "공정기술팀": [
    { skill_id: 9, target_level: 3, is_core: true },
    { skill_id: 64, target_level: 3, is_core: true },
    { skill_id: 66, target_level: 3, is_core: true },
    { skill_id: 120, target_level: 2, is_core: true },
    { skill_id: 124, target_level: 2, is_core: true },
    { skill_id: 68, target_level: 2, is_core: false },
    { skill_id: 70, target_level: 2, is_core: false },
    { skill_id: 127, target_level: 2, is_core: false },
  ],
};
